kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:18
    commands:
      - npm ci
  - name: test
    image: node:18
    commands:
      - npm test
  - name: publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
      email:
        from_secret: npm_email
    when:
      event:
        - tag
