name: 'NPM SemVer version'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  version:
    if: contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ukhomeoffice'

      - name: Calculate semver value
        id: calculate
        uses: UKHomeOffice/sas-github-workflows/.github/actions/calculate-semver-value@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}

      - name: Reset branch from main version
        id: compare
        run: |
          localFile=$(cat package.json)
          originFile=$(git show origin/main:package.json)
          localVersion=$(echo $localFile | jq -r '.version')
          originVersion=$(echo $originFile | jq -r '.version')
          if [ "$localVersion" != "$originVersion" ]; then
            npm --no-git-tag-version version $originVersion
          fi
        shell: bash

      - name: Bump release version
        run: |
          npm version --no-git-tag ${{ steps.calculate.outputs.version }}
        shell: bash

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        shell: bash

      - name: Commit version
        run: |
          git add "package.json"
          git add "package-lock.json"
          git commit -m "npm version ${{ steps.calculate.outputs.version }}"
          git push --set-upstream origin ${{ github.head_ref }} --force
