name: 'NPM SemVer version'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  version:
    if: contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ukhomeoffice'

      - name: Calculate semver value
        id: calculate
        uses: UKHomeOffice/sas-github-workflows/.github/actions/calculate-semver-value@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}

      - name: Bump release version
        run: |
          npm version --no-git-tag ${{ steps.calculate.outputs.version }}
        shell: bash

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.AUTH_TOKEN }}@github.com/UKHomeOffice/react-components.git
        shell: bash

      - name: Commit version
        run: |
          git add "package.json"
          git add "package-lock.json"
          git commit -m "npm version ${{ steps.calculate.outputs.version }}"
          git push --force
